# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import *
import pyqtgraph as pg
import serial
import serial.tools.list_ports
import socket  #导入socket模块
import time #导入time模块
PORT=8888
class MenuAction(QAction):
    def __init__(self, *__args):
        super().__init__(*__args)
        self.triggered.connect(lambda: self.click_event())
        self.is_clicked = 0

    def click_event(self):
        self.is_clicked = 1

    def click_event_clear(self):
        self.is_clicked = 0

class Ui_MainWindow(object):
    def __init__(self):
          super().__init__()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1038, 900)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMinimumSize(QtCore.QSize(1038, 0))
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setMouseTracking(False)
        self.centralwidget.setTabletTracking(False)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
           
        self.main = QtWidgets.QWidget()
        self.plot = QtWidgets.QWidget()
        self.figure = QtWidgets.QWidget()
        self.main.setObjectName("main")
        self.plot.setObjectName("plot")
        self.figure.setObjectName("figure")
        self.gridLayout = QtWidgets.QHBoxLayout(self.main)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.plot)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.figure)
        self.gridLayout.setObjectName("gridLayout") 
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.plot)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.tabWidget.addTab(self.main, "")
        self.initmain()
        # layout_func = QtWidgets.QHBoxLayout()  # 创建1级水平布局管理器layout_func
        # layout_func.setContentsMargins(0, 0, 10, 0)
        # self.gridLayout.addWidget(self.graph_win)  # 将图像窗口控件graph_win添加到0级布局管理器layout_win
        # self.gridLayout.addLayout(layout_func)  # 将1级布局管理器layout_func添加到0级布局管理器layout_win
        self.tabWidget.addTab(self.plot, "")
        self.initplot()
        self.tabWidget.addTab(self.figure, "")
        self.retranslateUi(MainWindow)
        #self.tabWidget.setCurrentIndex(0)
        #QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def initmain(self):
########################################################################
#########第一列
        # layout_label = QtWidgets.QVBoxLayout()
        # label1 = QtWidgets.QLabel()
        # label1.setText("I   P  :")
        # layout_label.addWidget(label1)
        # label1.move(6,1)
        # label2 =QtWidgets.QLabel()
        # label2.setText("端 口 号:")
        # layout_label.addWidget(label2)
        # label2.move(2,1)
        # label6 = QtWidgets.QLabel()
        # label6.setText("通道数量:")
        # layout_label.addWidget(label6)
        # label2.move(3,1)
        # label3 = QtWidgets.QLabel()
        # label3.setText("通信开关:")
        # label2.move(4,1)
        # layout_label.addWidget(label3)
        # self.gridLayout.addLayout(layout_label)
        #self.gridLayout.setContentsMargins(0, 0, 0, 0)
########################################################################
#########第二列        
        # layout_label_left = QtWidgets.QVBoxLayout()    
        # edit1 = QtWidgets.QLineEdit()
        # edit1.setInputMask('999_999_999_999;-') 
        # layout_label_left.addWidget(edit1,0)
        # edit2 = QtWidgets.QLineEdit()
        # edit2.textChanged.connect(self.textChanged)
        # layout_label_left.addWidget(edit2,1)
        # edit3 = QtWidgets.QLineEdit()
        # edit3.textChanged.connect(self.textChanged)
        # layout_label_left.addWidget(edit3,2)
        # edit4 = QtWidgets.QLineEdit()
        # edit4.textChanged.connect(self.textChanged)
        # layout_label_left.addWidget(edit4,3)
        # self.gridLayout.addLayout(layout_label_left,0.5)
        
 ########################################################################
#########第三列       
        
        # layout_label_right = QtWidgets.QVBoxLayout()
        # label_r2 = QtWidgets.QLabel()
        # label_r2.setText(" 缓存大小:")
        # layout_label_right.addWidget(label_r2)
        # label_r2 = QtWidgets.QLabel()
        # label_r2.setText(" 输入指令:")
        # layout_label_right.addWidget(label_r2)
        # label_r2 = QtWidgets.QLabel()
        # label_r2.setText(" 文本显示:")
        # layout_label_right.addWidget(label_r2)
        # label_r2 = QtWidgets.QLabel()
        # label_r2.setText(" 清空显示:")
        # layout_label_right.addWidget(label_r2)
        # self.gridLayout.addLayout(layout_label_right,0.5)
        
        
        
        
 ########################################################################
#########第四列       
        #layout_key_right = QtWidgets.QVBoxLayout()
        # 图像缓存大小设置按键
        # self.key_graph_len = QtWidgets.QPushButton()
        # menu_graph_len = QMenu(self.key_graph_len)
        # action_graph_len0 = QAction("100", menu_graph_len)  # 创建动作
        # action_graph_len1 = QAction("200", menu_graph_len)
        # action_graph_len2 = QAction("500", menu_graph_len)
        # action_graph_len3 = QAction("1000", menu_graph_len)
        # action_graph_len0.triggered.connect(lambda: self.graph_set_len_x(100))  # 连接动作触发信号
        # action_graph_len1.triggered.connect(lambda: self.graph_set_len_x(200))
        # action_graph_len2.triggered.connect(lambda: self.graph_set_len_x(500))
        # action_graph_len3.triggered.connect(lambda: self.graph_set_len_x(1000))
        # menu_graph_len.addAction(action_graph_len0)  # 添加动作到菜单
        # menu_graph_len.addAction(action_graph_len1)
        # menu_graph_len.addAction(action_graph_len2)
        # menu_graph_len.addAction(action_graph_len3)
        # self.key_graph_len.setMenu(menu_graph_len)
        # layout_key_right.addWidget(self.key_graph_len)
        # 开关图像显示按键
        # self.key_graph_switch = QtWidgets.QPushButton()
        # self.key_graph_switch.clicked.connect(lambda: self.graph_on())
        # layout_key_right.addWidget(self.key_graph_switch)
        # 开关文本显示按键
        # self.key_text_switch = QtWidgets.QPushButton()
        # self.key_text_switch.clicked.connect(lambda: self.text_on())
        # layout_key_right.addWidget(self.key_text_switch)
        # 文本清除按键
        # key_text_clean = QtWidgets.QPushButton(QIcon(":/images/clean_icon.png"), "")
        # key_text_clean.clicked.connect(lambda: self.clear_all())
        # layout_key_right.addWidget(key_text_clean)

        # self.gridLayout.addLayout(layout_key_right,0.5)
        
        # layout_key = QtWidgets.QVBoxLayout()  # 创建2级垂直布局管理器layout2
        # 串口列表按键
    
        self.label_3 = QtWidgets.QLabel(self.main)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.main)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 11, 1, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.main)
        self.comboBox_7.setObjectName("comboBox_7")
        self.gridLayout.addWidget(self.comboBox_7, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.main)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.main)
        self.comboBox_8.setObjectName("comboBox_8")
        self.gridLayout.addWidget(self.comboBox_8, 5, 1, 1, 1)
        
        self.label_7 = QtWidgets.QLabel(self.main)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
       
        self.line = QtWidgets.QFrame(self.main)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 8, 0, 1, 1)
        """添加波特率并且设置数值"""
       
        self.label_2 = QtWidgets.QLabel(self.main)       #波特率选择
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.main)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 11, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.main)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem('1200')
        self.comboBox_2.addItem('9600')
        self.comboBox_2.addItem('38400')
        self.comboBox_2.addItem('115200')
        self.gridLayout.addWidget(self.comboBox_2, 2, 1, 1, 1)
        
        self.comboBox_3 = QtWidgets.QComboBox(self.main)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout.addWidget(self.comboBox_3, 3, 1, 1, 1)
        
        self.label_8 = QtWidgets.QLabel(self.main)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.main)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 8, 1, 1, 1)
        # self.checkBox = QtWidgets.QCheckBox(self.main)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 12, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.main)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 12, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.main)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 6, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.main)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.main)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 11, 2, 3, 1)
        self.textEdit = QtWidgets.QTextEdit(self.main)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 2, 7, 1)
        
    
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.figure)
        
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        #self.menubar = QtWidgets.QMenuBar(MainWindow)
        #self.menubar.setGeometry(QtCore.QRect(0, 0, 1038, 26))
        #self.menubar.setObjectName("menubar")
        #self.menumain = QtWidgets.QMenu(self.menubar)
        #self.menumain.setObjectName("menumain")
        #MainWindow.setMenuBar(self.menubar)
        #self.menubar.addAction(self.menumain.menuAction())
    def initplot(self):
        self.graph_win = pg.GraphicsLayoutWidget(self.plot)  # 创建图像窗口控件graph_win
        self.graph0 = self.graph_win.addPlot()  # 创建图像graph0
        self.curve0 = self.graph0.plot(pen="r")  # 创建曲线curve0
        self.curve1 = self.graph0.plot(pen="g")
        self.curve2 = self.graph0.plot(pen="b")
        self.curve3 = self.graph0.plot(pen="w")
        self.curve4 = self.graph0.plot(pen="r")  # 创建曲线curve0
        self.curve5 = self.graph0.plot(pen="g")
        self.curve6 = self.graph0.plot(pen="b")
        self.curve7 = self.graph0.plot(pen="w")
        layout_func = QtWidgets.QVBoxLayout(self.plot)  # 创建1级水平布局管理器layout_func
        layout_func.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_2.addWidget(self.graph_win)  # 将图像窗口控件graph_win添加到0级布局管理器layout_win
        self.horizontalLayout_2.addLayout(layout_func)  # 将1级布局管理器layout_func添加到0级布局管理器layout_win
   
    def graph_set_len_x(self, len_x):
            self.max_len_x = len_x
    def textChanged(self,text):
            print('输入的内容：' + text)
        # self.key_graph_len.setText(str(self.max_len_x))
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "2018级自动化1班刘宇辰毕业设计"))
        self.pushButton_8.setText(_translate("MainWindow", "手动发送"))
        self.label.setText(_translate("MainWindow", "端口"))
        self.label_7.setText(_translate("MainWindow", "数据位"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "5"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "6"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "7"))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "8"))
        self.label_2.setText(_translate("MainWindow", "波特率"))

        self.pushButton_7.setText(_translate("MainWindow", "清空接受区"))
        self.label_8.setText(_translate("MainWindow", "停止位"))
        self.checkBox.setText(_translate("MainWindow", "十六进制"))
        self.checkBox_2.setText(_translate("MainWindow", "十进制"))
        self.pushButton_2.setText(_translate("MainWindow", "打开串口"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "校验位"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main), _translate("MainWindow", "主要信息"))
        self.pushButton.setText(_translate("MainWindow", "2222"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.plot), _translate("MainWindow", "绘图"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.figure), _translate("MainWindow", "数据库"))
        self.menumain.setTitle(_translate("MainWindow", "主窗口"))
if __name__ == '__main__':
    import sys
    from PyQt5.QtWidgets import QApplication, QMainWindow
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
